services:
  oopt-gnpy-web-ui:
    image: networkwize/oopt-gnpy-web-ui:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm start
